<a href="https://colab.research.google.com/github/nalinis07/PRO_Colabs/blob/MASTER/PRO_C124_Reference_code.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

What is a **Matrix**?

We know that is it the arrangement of numbers in tabular form. In Python, we use 2D lists or arrays to represent a matrix. A Matrix should always have a numerical value.

1D list: It is the list with one row and many columns as shown.

2D list: It is the list of lists. It can have any number of rows and columns.


In [ ]:
# Method 1 to create a 1D and 2D list
A = [3,2,-1,9,5]
print(A)
B =[[1,-2,3],[8,4,6],[-6,5,3]]
print(B)

[3, 2, -1, 9, 5]
[[1, -2, 3], [8, 4, 6], [-6, 5, 3]]


**NumPy** library provides different dedicated operations on arrays and provides faster operations on arrays.

In [ ]:
#Method to create a 1D array using NumPy

import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
#Method-2 to create a 2D array using NumPy

arr_2d =np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr_2d)
type(arr_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


numpy.ndarray

In [ ]:
#Array with elements of different data types

arr_2d_1 =np.array([[1,2,3],['a',5,True],[7,8,9]])
print(arr_2d_1)
type(arr_2d_1)

[['1' '2' '3']
 ['a' '5' 'True']
 ['7' '8' '9']]


numpy.ndarray

Accessing elements of 2D lists and arrays

In [ ]:
#Accessing elements of 1D list or array
print(A)
print(A[1])
print(arr)
print(arr[2])

[3, 2, -1, 9, 5]
2
[1 2 3 4 5]
3


In [ ]:
#accessing elements of 2D array method1
print(arr_2d)
print(arr_2d[1,2])
#accessing elements of 2D array method2
print(arr_2d[0][1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
6
2


Updating elements of 2D Lists

In [ ]:
#To update an element from 2D list/arrays
print(arr_2d)
print('----------------')
# method 1
arr_2d[1,2]=-4
print(arr_2d)
print('----------------')
# method 2
arr_2d[1,2]=8
print(arr_2d)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
----------------
[[ 1  2  3]
 [ 4  5 -4]
 [ 7  8  9]]
----------------
[[1 2 3]
 [4 5 8]
 [7 8 9]]


Add/Subtract elements of 2D lists

In [ ]:
a=np.array([[1,3],
            [5,4]])
b=np.array([[7,8],
            [6,9]])
rows=2
cols=2
c=[[0,0],
   [0,0]]
for i in range(rows):
  for j in range(cols):
    c[i][j]=a[i][j]+b[i][j]
print(a,'\n')
print(b,'\n')
print(c)

[[1 3]
 [5 4]] 

[[7 8]
 [6 9]] 

[[8, 11], [11, 13]]


Multiply elements of 2D lists

Scalar Multiplication

In [ ]:
b=np.array([[2,-2],
            [0,5],
            [4,7]])      # 3x2 matrix

print(b,'\n')
n=5                      #scalar
mul=np.zeros([3,2])
for i in range(3):
  for j in range(2):
    #print(b[i][j])
    mul[i][j]= n* b[i][j]
    #print(mul[i][j])


for rows in mul:
  print(rows)

[[ 2 -2]
 [ 0  5]
 [ 4  7]] 

[ 10. -10.]
[ 0. 25.]
[20. 35.]


In [ ]:
#Use the multiply() method

n = 5     #scalar

arr1= np.array([1, 2, 3])
arr2=np.multiply(arr1,n)
print(arr2)
print('---------------------')

arr3= np.array([[1, 2],
                [3, 4]])
arr4=np.multiply(arr,n)
print(arr4)
print('---------------------')

print(a)
e=np.multiply(a,n)
print(e)

[ 5 10 15]
---------------------
[ 5 10 15 20 25]
---------------------
[[1 3]
 [5 4]]
[[ 5 15]
 [25 20]]


In [ ]:
#Additional Activity
#To multiply elements of 2D list/arrays

a=np.array([[2,3,-4],
             [6,1,0],
             [8,9,3]])    # 3x3 matrix

b=np.array([[2,-2],
            [0,5],
            [4,7]])      # 3x2 matrix

c= np.zeros([3,2])

print(c,'\n')
rows_a=3
cols_a=rows_b=2
cols_b=3

for i in range(3):
  for j in range(2):
    for k in range(3):
      c[i][j]=c[i][j]+a[i][k]*b[k][j]
      #print(c[i][j])


for rows in c:
  print(rows)

[[0. 0.]
 [0. 0.]
 [0. 0.]] 

[-12. -17.]
[12. -7.]
[28. 50.]
